In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
#sentance
sent = ['the glass of milk',
       'the glass of juice',
        'the cup of tea',
        'i am a good boy',
        'i am a good developer',
        'understand a meaning of word',
        'your videos is very good'
       ]

In [6]:
print(sent)

['the glass of milk', 'the glass of juice', 'the cup of tea', 'i am a good boy', 'i am a good developer', 'understand a meaning of word', 'your videos is very good']


In [7]:
#vocabulary size
voc_size = 1000

# One hot representation

In [8]:
onehot_represent = [one_hot(words,voc_size)for words in sent]
print(onehot_represent)

[[900, 385, 766, 137], [900, 385, 766, 559], [900, 505, 766, 416], [188, 540, 843, 995, 256], [188, 540, 843, 995, 120], [339, 843, 99, 766, 638], [453, 779, 158, 951, 995]]


# Word Embeddings Representation

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [13]:
import numpy as np

In [14]:
sent_length = 8

In [15]:
embedded_docs = pad_sequences(onehot_represent,maxlen=sent_length,padding='pre')
print(embedded_docs)

[[  0   0   0   0 900 385 766 137]
 [  0   0   0   0 900 385 766 559]
 [  0   0   0   0 900 505 766 416]
 [  0   0   0 188 540 843 995 256]
 [  0   0   0 188 540 843 995 120]
 [  0   0   0 339 843  99 766 638]
 [  0   0   0 453 779 158 951 995]]


In [17]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))    #2nd parameter how many dimention we want to take
model.compile(optimizer='adam',loss= 'mse')

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             10000     
                                                                 
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(model.predict(embedded_docs))

1/1 [==============================] - 2s 2s/step
[[[ 0.00349585 -0.0154326  -0.03933597 -0.02076157  0.03669893
   -0.00862676  0.02511562  0.00087257 -0.01637834 -0.01108326]
  [ 0.00349585 -0.0154326  -0.03933597 -0.02076157  0.03669893
   -0.00862676  0.02511562  0.00087257 -0.01637834 -0.01108326]
  [ 0.00349585 -0.0154326  -0.03933597 -0.02076157  0.03669893
   -0.00862676  0.02511562  0.00087257 -0.01637834 -0.01108326]
  [ 0.00349585 -0.0154326  -0.03933597 -0.02076157  0.03669893
   -0.00862676  0.02511562  0.00087257 -0.01637834 -0.01108326]
  [ 0.01334213  0.01969353  0.04974948  0.04340914 -0.03671166
    0.02163934  0.01781556 -0.00901075  0.00010026 -0.00630661]
  [ 0.00412812 -0.03128209  0.01882073 -0.00719219  0.00295073
   -0.03629474 -0.03127756 -0.01023161  0.00710392  0.04129401]
  [ 0.00398717  0.02798608 -0.02372739 -0.02506289  0.02127328
   -0.02299955 -0.04348481 -0.02732607 -0.0468266   0.00410186]
  [-0.04126521 -0.04578594 -0.01890812 -0.04435509  0.0004443

In [20]:
embedded_docs[0]

array([  0,   0,   0,   0, 900, 385, 766, 137])

In [21]:
print(model.predict(embedded_docs[0]))

1/1 [==============================] - 0s 50ms/step
[[ 0.00349585 -0.0154326  -0.03933597 -0.02076157  0.03669893 -0.00862676
   0.02511562  0.00087257 -0.01637834 -0.01108326]
 [ 0.00349585 -0.0154326  -0.03933597 -0.02076157  0.03669893 -0.00862676
   0.02511562  0.00087257 -0.01637834 -0.01108326]
 [ 0.00349585 -0.0154326  -0.03933597 -0.02076157  0.03669893 -0.00862676
   0.02511562  0.00087257 -0.01637834 -0.01108326]
 [ 0.00349585 -0.0154326  -0.03933597 -0.02076157  0.03669893 -0.00862676
   0.02511562  0.00087257 -0.01637834 -0.01108326]
 [ 0.01334213  0.01969353  0.04974948  0.04340914 -0.03671166  0.02163934
   0.01781556 -0.00901075  0.00010026 -0.00630661]
 [ 0.00412812 -0.03128209  0.01882073 -0.00719219  0.00295073 -0.03629474
  -0.03127756 -0.01023161  0.00710392  0.04129401]
 [ 0.00398717  0.02798608 -0.02372739 -0.02506289  0.02127328 -0.02299955
  -0.04348481 -0.02732607 -0.0468266   0.00410186]
 [-0.04126521 -0.04578594 -0.01890812 -0.04435509  0.00044432 -0.02185992

In [22]:
#congratulations.....  we got embedding of word 